[build]
  command = "npm run build"
  publish = "build" # (ou "public" selon la config de Vite)

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[edge_functions]]
function = "log"
path = "/test"